### PR TITLE
Update build process

### LINKED ISSUE #28: Typescript spits out errors during build
This is because `webextension-polyfill-ts`decided to return `{}` instead of the actual module if it can't detect a window: https://github.com/Lusito/webextension-polyfill-ts/blob/master/src/generated/index.ts#L154-L156

Either define the window somehow or clone and maintain a new version

### PR DESCRIPTION
**Pull request by jwoos**
1. Fixed TypeScript not loading the `webextension-polyfill-ts` by changing module resolution method to be Node
2. Webpack now shows all built modules - the default was to hide some. It's much easier to debug now. 
3. Webpack also logs information from `ts-loader` now. Better for debugging.
4. Cleaned up `tsc` options and specified files to run it on. When run with `--noEmit` it's a type checking tool.
    a. Support for modules seems pretty good though so we might want to even ditch bundlers: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
5. Added Parcel as a new option. It's zero configuration but it does not show any errors on build. However, we can just run `tsc` as a type checker prior to building! `scripts/build-new.sh` is the new script. Left the old one for now.

Resolves #28

### CODE REVIEW

**Comment by jwoos** [comment]
@dqgorelick can you take a look when you get the chance?

**Comment by dqgorelick** [comment]
The "instructions" and "keybinds" buttons aren't doing anything for me in firefox.

**Comment by dqgorelick** [comment]
They also aren't working for me in Chrome :/

**Comment by jwoos** [comment]
Will take a look

**Comment by jwoos** [comment]
@dqgorelick fixed branch - tested on both ff and chrome

**Pull request merged**
